[package]
name = "tungstenite"
description = "Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming"]
keywords = ["websocket", "io", "web"]
authors = ["Alexey Galakhov"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/snapview/tungstenite-rs"
documentation = "https://docs.rs/tungstenite/0.2.4"
repository = "https://github.com/snapview/tungstenite-rs"
version = "1.0.0"

[features]
default = ["tls"]
tls = ["native-tls"]

[dependencies]
base64 = "0.5.2"
byteorder = "1.0.0"
bytes = "0.4.3"
httparse = "1.2.2"
log = "0.3.7"
rand = "0.3.15"
sha1 = "0.2.0"
url = "1.4.0"
utf-8 = "0.7.1"

[dependencies.native-tls]
optional = true
version = "0.1.2"

[dev-dependencies]
env_logger = "0.4.2"
